get http://localhost:3003/api/blogs

###

post http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "Test2",
    "author": "GM",
    "url": "none",
    "likes": 233
}

###
delete http://localhost:3003/api/blogs/60439b0e37e6b89c625e7d41

###

put http://localhost:3003/api/blogs/604e4919e9c8f456ef394485
content-type: application/json

{
    "title": "TEST3",
    "author": "GM",
    "url": "none",
    "likes": 233
}